#!/bin/sh


# Verbosity where useful
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	cat="bat --plain --theme OneHalfDark "

# Colorize commands when possible
alias \
	ls="exa --color=auto"
	grep="rg" \
	diff="diff --color=auto"

# Abbreviations
alias \
	c="clear" \
	l="exa -lah --no-filesize --git" \
	..="cd .." \
	...="cd ../.." \
	....="cd ../../.." \
	.....="cd ../../../.." \
	......="cd ../../../../.." \
	t="clear; exa --tree --icons" \
	t1="t -L1" \
	t2="t -L2" \
	t3="t -L3" \
	t4="t -L4" \
	t5="t -L5" \
	t6="t -L6" \
    open="xdg-open" \
    claws-mail="claws-mail --alternate-config-dir $XDG_CONFIG_HOME/claws-mail"

# Make aliasrc POSIX-compliant. Only load if command exists for this shell
if command -v pushd &> /dev/null
then
    # Own sciptings
    # Cache cd-usages
    alias cd='pushd 1> /dev/null'
    # Traverse cd-usages back in time
    alias u='popd 1> /dev/null'
fi
# Download music from YouTube
alias music-dl="youtube-dl -x --audio-format opus --audio-quality 0 --prefer-ffmpeg"
# List available wifi-networks
alias net-list="nmcli device wifi list"
# Connect to wifi-network with given SSID
alias net-connect="nmcli device wifi connect --ask"

alias eduroam-connect='sudo systemctl stop NetworkManager; sudo killall wpa_supplicant; sudo systemctl start dhcpcd; sudo wpa_supplicant -i wlan0 -c /etc/wpa_supplicant/eduroam.conf &'

alias print='sudo systemctl start cups; lp -d ts5000'
# There is no reason, why the printing-deamon should run all the time.
alias print-end='sudo systemctl stop cups'

# Fuzzy Find
alias fzf="fzf --preview 'bat --style=numbers --color=always --line-range :500 {}'"

function fuzzy_nvim_start {
    if [ "$#" -eq 0 ]; then
        nvim +'Telescope find_files hidden=true layout_config={height=0.9}'
    else
        nvim $@
    fi
}
alias v='fuzzy_nvim_start'

## git
alias gs='git status --short'
alias gd='git diff'
alias ga='git add'
alias gc='git commit'
alias gp='git pull'
alias gpp='git push'

