#!/bin/sh


# Verbosity where useful
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	cat="bat --plain --theme OneHalfDark "

# Colorize commands when possible
alias \
	ls="exa --color=auto"
	grep="grep --color=auto" \
	diff="diff --color=auto"

# Abbreviations
alias \
	e="emacs" \
	c="clear" \
	v="$EDITOR" \
	l="exa -lah" \
	..="cd .." \
	...="cd ../.." \
	....="cd ../../.." \
	.....="cd ../../../.." \
	......="cd ../../../../.." \
	t="clear; exa --tree" \
	t1="clear; exa --tree -L1" \
	t2="clear; exa --tree -L2" \
	t3="clear; exa --tree -L3" \
	t4="clear; exa --tree -L4" \
	t5="clear; exa --tree -L5" \
	t6="clear; exa --tree -L6" \

# Make aliasrc POSIX-compliant. Only load if command exists for this shell
if command -v pushd &> /dev/null
then
    # Own sciptings
    # Cache cd-usages
    alias cd='pushd 1> /dev/null'
    # Traverse cd-usages back in time
    alias u='popd 1> /dev/null'
fi
# Download music from YouTube
alias music-dl="youtube-dl -x --audio-format opus --audio-quality 0 --prefer-ffmpeg"
# List available wifi-networks
alias net-list="iwctl station wlan0 scan && iwctl station wlan0 get-networks"
# Connect to wifi-network with given SSID
alias net-connect="iwctl station wlan0 connect"

