#!/bin/sh


# Deactivate creation of python_history
export PYTHONSTARTUP=~/.config/python/pythonrc

export PATH="$PATH:$HOME/.local/bin:$HOME/.local/share/cargo/bin:$HOME/.emacs.d/bin:"
unsetopt PROMPT_SP

# Default programs
export EDITOR="/usr/bin/nvim"
export TERMINAL="/usr/bin/alacritty"
export BROWSER="/usr/bin/qutebrowser"

# Home cleanup
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.cache
export XINITRC=$XDG_CONFIG_HOME/x11/xinitrc
export XCOMPOSEFILE=$XDG_CONFIG_HOME/x11/xcompose
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export INPUTRC=$XDG_CONFIG_HOME/shell/inputrc
export ZDOTDIR=$XDG_CONFIG_HOME/zsh
export DOORDIR=$XDG_CONFIG_HOME/doom
export DOCKER_CONFIG=$XDG_CONFIG_HOME/docker
# deactivate creation of less-histfile
export LESSHISTFILE=-
export PASSWORD_STORE_DIR=$XDG_DATA_HOME/password-store
export GNUPGHOME=$XDG_DATA_HOME/gnupg
export STARSHIP_CONFIG=$XDG_CONFIG_HOME/zsh/starship/starship.toml
export RUSTUP_HOME=$XDG_DATA_HOME/rustup
export CARGO_HOME=$XDG_DATA_HOME/cargo
export GOPATH=$XDG_DATA_HOME/go
export GOMODCACHE=$XDG_DATA_HOME/go/mod

# Own scripts-directory
export PYNNACLE_DATA=$XDG_DATA_HOME/pynnacle


# Application-specific configurations
export FZF_COMPLETION_TRIGGER=,,
export FZF_COMPLETION_OPTS='--hidden --exclude ".git" --preview="bat"'
# NNN is only configured through ENV-vars, so these are bundles accordingly
source $XDG_CONFIG_HOME/nnn/config.nnn
export LS_COLORS="$(vivid generate everforest)"


if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
    # use custom-placed xinitrc, so it does not clutter the home-dir
	exec startx $XINITRC
fi

