#!/bin/sh

# Restart nitrogen with previously used wallpaper/configurations
dunst &
unclutter &
exec picom &
# Start program to notify on changing home-directory
sh $XDG_DATA_HOME/pynnacle/watch-home.sh

# Finally, start window-manager
qtile start
