#!/bin/sh

# Load Xresources-file in custom location
xrdb -I$XDG_CONFIG_HOME/x11 $XDG_CONFIG/HOME/x11/Xresources

# Set certain Wallpaper
xwallpaper --zoom ~/Pictures/wallpapers/archcraft/archcraft-backgrounds/files/forest.jpg

# Set random lockscreen
# Move to background since this command takes a little while
betterlockscreen -u ~/Pictures/lockscreens/ &

dunst &
unclutter &
picom -b
# Start program to notify on changing home-directory
sh $XDG_DATA_HOME/pynnacle/watch-home.sh &

# Finally, start window-manager
exec spectrwm
