#!/bin/sh

# Load Xresources-file in custom location.
xrdb -I$XDG_CONFIG_HOME/x11 $XDG_CONFIG_HOME/x11/Xresources

# Set certain Wallpaper.
xwallpaper --zoom ~/Pictures/wallpapers/purple.jpg

# Set random lockscreen.
# Move to background since this command takes a little while.
betterlockscreen -u ~/Pictures/lockscreens/ &

dunst &
unclutter &
udiskie &
picom -b
conky --config=$XDG_CONFIG_HOME/conky/conky-quotem.conf -d
# conky --config=$XDG_CONFIG_HOME/conky/conky-taskwarrior.conf -d
flameshot &
# Start program to notify on changing home-directory.
sh $XDG_DATA_HOME/pynnacle/watch-home.sh &

# set mouse-knob sensitivity
xinput set-prop 'TPPS/2 Elan TrackPoint' 'libinput Accel Speed' -0.3
xinput set-prop 'SynPS/2 Synaptics TouchPad' 'Device Enabled' 0

# Finally, start window-manager.
exec /bin/qtile start
#exec spectrwm
